### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by Jasonwu123** [filswan/js-mcs-sdk#1]
When I run the js-mcs-sdk test.js:

```
PS C:\Users\12109\Desktop\mcs-client> node .\test.js
TypeError: Cannot read properties of undefined (reading 'name')
at FormData._getContentDisposition (C:\Users\12109\node_modules\form-data\lib\form_data.js:227:40)
at FormData._multiPartHeader (C:\Users\12109\node_modules\form-data\lib\form_data.js:178:33)
at FormData.append (C:\Users\12109\node_modules\form-data\lib\form_data.js:71:21)
at uploadPromise (C:\Users\12109\node_modules\mcs-client\helper\upload.js:16:8)
at C:\Users\12109\node_modules\mcs-client\helper\upload.js:39:7
at async Promise.all (index 0)
at async mcsUpload (C:\Users\12109\node_modules\mcs-client\helper\upload.js:52:20)
at async mcsClient.upload (C:\Users\12109\node_modules\mcs-client\index.js:54:5)
at async test (C:\Users\12109\Desktop\mcs-client\test.js:21:26)
C:\Users\12109\Desktop\mcs-client\test.js:22
console.log(uploadResponse[0].data.payload_cid)
^

TypeError: Cannot read properties of undefined (reading '0')
at test (C:\Users\12109\Desktop\mcs-client\test.js:22:29)
```

Here is the test.js code :

```
require('dotenv').config('C:\\Users\\12109\\.env')
const fs = require('fs')
const { mcsClient } = require('mcs-client')


const client = new mcsClient({
  privateKey: process.env.PRIVATE_KEY,
})

const test = async  () => {
  const fileArray = [
    { fileName: 'jstest', file: fs.createReadStream('./jstest.txt') },
  ]

  const options = {
    delay: 1000, 
    duration: 180, 
    fileType: 0, 
  }

  const uploadResponse = await client.upload(fileArray, options)
  console.log(uploadResponse[0].data.payload_cid)
  console.log(uploadResponse[0].data.ipfs_url)
}

test()
```

node and npm version: 

```
PS C:\Users\12109\Desktop\mcs-client> node -v
v16.13.1
PS C:\Users\12109\Desktop\mcs-client> npm -v
8.1.2
PS C:\Users\12109\Desktop\mcs-client>
```

What's wrong with me???

**Comment by rykci** [comment]
Your MCS Client also needs `rpcUrl`. You can get one here: https://www.alchemy.com/

```
const client = new mcsClient({
  privateKey: process.env.PRIVATE_KEY,
  rpcUrl: process.env.RPC_URL
})
```

**Comment by Jasonwu123** [comment]
No, the rpcUrl is not matter. Because the mcs-sdk's index.js has a default rpcUrl :

```
constructor({
    privateKey,
    rpcUrl = 'https://matic-mumbai.chainstacklabs.com',
  }) {
    this.version = packageJson.version
    this.web3 = new Web3(rpcUrl)
    if (privateKey) {
      this.setAccount(privateKey)
    }
  }
```

Ok, I try it in my macbook, but the error is the same as the win10:

```
TypeError: Cannot read properties of undefined (reading 'name')
    at FormData._getContentDisposition (/Users/jasonwu/node_modules/form-data/lib/form_data.js:227:40)
    at FormData._multiPartHeader (/Users/jasonwu/node_modules/form-data/lib/form_data.js:178:33)
    at FormData.append (/Users/jasonwu/node_modules/form-data/lib/form_data.js:71:21)
    at uploadPromise (/Users/jasonwu/node_modules/mcs-client/helper/upload.js:16:8)
    at /Users/jasonwu/node_modules/mcs-client/helper/upload.js:39:7
    at async Promise.all (index 0)
    at async mcsUpload (/Users/jasonwu/node_modules/mcs-client/helper/upload.js:52:20)
    at async mcsClient.upload (/Users/jasonwu/node_modules/mcs-client/index.js:54:5)
    at async test (/Users/jasonwu/Code/nodejs/test.js:23:28)
/Users/jasonwu/Code/nodejs/test.js:24
    console.log(uploadResponse[0].data.payload_cid)
                              ^

TypeError: Cannot read properties of undefined (reading '0')
    at test (/Users/jasonwu/Code/nodejs/test.js:24:31)
```

show the code:

```
require('dotenv').config('/Users/jasonwu/.env')
const fs = require('fs')
const { mcsClient } = require('mcs-client')


const client = new mcsClient({
    privateKey: process.env.PRIVATE_KEY,
    rpcUrl: process.env.RPC_URL,
})

const test = async() => {

    const fileArray = [
        { fileName: 'jstest', file: fs.createReadStream('./jstest.txt') },
    ]

    const options = {
        delay: 1000,
        duration: 180,
        fileType: 0,
    }

    const uploadResponse = await client.upload(fileArray, options)
    console.log(uploadResponse[0].data.payload_cid)
    console.log(uploadResponse[0].data.ipfs_url)
}

test()
```

**Comment by flyworker** [comment]
the rpc url may has some issue:
https://rpc-mumbai.matic.today/ or
https://matic-mumbai.chainstacklabs.com/ or
https://rpc-mumbai.maticvigil.com/ or
https://matic-testnet-archive-rpc.bwarelabs.com/

for now 
https://rpc-mumbai.maticvigil.com is working

**Comment by flyworker** [comment]
@rykci  maybe we should move the rpc to config file?

**Comment by rykci** [comment]
@Jasonwu123 Yes, it seems like the default RPC has some issue. Also check to make sure your env variables are being loading in correctly.

**Comment by Jasonwu123** [comment]
Sorry, because the .env file is error. copy it in the current dir is fine.
Thank you very one!
